# Generated by Django 4.2 on 2023-04-08 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_order_payment"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="payment",),
        migrations.RemoveField(model_name="order", name="price",),
        migrations.RemoveField(model_name="order", name="product",),
        migrations.RemoveField(model_name="order", name="quantity",),
        migrations.RemoveField(model_name="transaction", name="order",),
        migrations.AddField(
            model_name="order",
            name="transaction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shop.transaction",
            ),
            preserve_default=False,
        ),
    ]
