# Generated by Django 4.2 on 2023-04-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_remove_order_payment_remove_order_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="no_cart_item",
            field=models.PositiveIntegerField(default=1, max_length=2434000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="total",
            field=models.DecimalField(
                decimal_places=3, default=0.0, max_digits=10, max_length=10
            ),
        ),
    ]
