# Generated by Django 4.2 on 2023-04-09 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_payment_balance"),
        ("shop", "0005_cart_no_cart_item_cart_total"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="no_cart_item",),
        migrations.RemoveField(model_name="cart", name="total",),
        migrations.RemoveField(model_name="order", name="transaction",),
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="account.payment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shop.order",
            ),
            preserve_default=False,
        ),
    ]
