# Generated by Django 4.2 on 2023-04-10 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0006_remove_cart_no_cart_item_remove_cart_total_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="transaction", name="order",),
        migrations.AddField(
            model_name="cartitem",
            name="person",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="transaction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shop.transaction",
            ),
            preserve_default=False,
        ),
    ]
