# Generated by Django 4.2 on 2023-04-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_remove_transaction_order_cartitem_person_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="payment",),
        migrations.AlterField(
            model_name="order",
            name="transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shop.transaction",
            ),
        ),
    ]
