# Generated by Django 4.2 on 2023-04-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_payment_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=8, max_length=8
            ),
        ),
    ]
